# Copyright 2022-2023 Datum Technology Corporation
# All rights reserved.
########################################################################################################################


[project]
name        = "core-v-mcu-uvm"
full-name   = "CORE-V MCU UVM Test Bench Project"
description = ""

[simulation]
uvm-version       = "1.2"
timescale         = "1ns/1ps"
default-simulator = "mdc"

[ip]
paths = ["dv", "dv/agents", "dv/blocks", "dv/chip", "dv/ss", "rtl", "rtl/core-v-mcu"]