# Copyright 2022 Datum Technology Corporation
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
########################################################################################################################


[project]
name        = "core-v-mcu-uvm"
full-name   = "CORE-V MCU UVM"
description = ""

[simulation]
preferred-simulators = [ "vivado" ]
