# Copyright 2022 Datum Technology Corporation
# All rights reserved.
########################################################################################################################


[project]
name        = "core-v-mcu-uvm"
full-name   = "CORE-V MCU UVM"
description = ""

[simulation]
default-simulator = "viv"

[ip]
paths = ["dv", "rtl", "rtl/core-v-mcu"]
global-paths = ["/home/dpoulin/git/uvma_apb/dv", "/homes/dpoulin/git/uvma_obi/dv", "/homes/dpoulin/git/uvmx/dv"]
